import {
  AiGeneration,
  ContentBrief,
  KeywordCluster,
  PageBrief,
  PlannedPage,
  Report,
  ReportSection,
  SeoStrategy,
  Sop,
  SopStep,
} from "@/lib/agency-os/phase3/types";

function ts(day: string): string {
  return `${day}T12:00:00.000Z`;
}

const seoStrategies: SeoStrategy[] = [
  {
    id: "seo-bluepeak-01",
    createdAt: ts("2026-04-08"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-bluepeak",
    clientName: "BluePeak Roofing",
    owner: "Maya Lee",
    title: "BluePeak Local Service Expansion",
    serviceFocus: ["roof repair", "roof replacement", "storm damage"],
    targetLocations: ["Austin", "Round Rock", "Cedar Park"],
    schemaOpportunities: ["LocalBusiness", "FAQPage", "Service"],
    internalLinkOpportunities: [
      "Link location pages to emergency repair page",
      "Cross-link financing content into replacement pages",
    ],
    faqTargets: ["How fast can repairs start?", "What financing options exist?"],
    strategyBrief:
      "Prioritize high-intent emergency and replacement pages with city-specific trust proof and focused CTA paths.",
    status: "active",
  },
  {
    id: "seo-luna-01",
    createdAt: ts("2026-04-05"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-luna",
    clientName: "Luna Legal Group",
    owner: "Jordan Price",
    title: "Luna Local Practice Area Growth",
    serviceFocus: ["personal injury", "employment law"],
    targetLocations: ["Phoenix", "Scottsdale", "Mesa"],
    schemaOpportunities: ["LegalService", "FAQPage"],
    internalLinkOpportunities: ["Link practice pages to case result proof hubs"],
    faqTargets: ["What does consultation include?", "How are fees structured?"],
    strategyBrief:
      "Build city + practice matrix with unique legal proof blocks to reduce duplication risk and increase lead confidence.",
    status: "active",
  },
];

const keywordClusters: KeywordCluster[] = [
  {
    id: "cluster-bluepeak-emergency",
    createdAt: ts("2026-04-09"),
    updatedAt: ts("2026-04-22"),
    strategyId: "seo-bluepeak-01",
    clusterName: "Emergency Roofing",
    primaryKeyword: "emergency roof repair austin",
    secondaryKeywords: ["24 hour roof repair", "storm roof leak repair"],
    intent: "transactional",
    priorityScore: 92,
  },
  {
    id: "cluster-luna-injury",
    createdAt: ts("2026-04-07"),
    updatedAt: ts("2026-04-22"),
    strategyId: "seo-luna-01",
    clusterName: "Injury Case Intake",
    primaryKeyword: "personal injury lawyer phoenix",
    secondaryKeywords: ["injury attorney consultation", "accident lawyer near me"],
    intent: "commercial",
    priorityScore: 89,
  },
];

const plannedPages: PlannedPage[] = [
  {
    id: "plan-bluepeak-austin-repair",
    createdAt: ts("2026-04-10"),
    updatedAt: ts("2026-04-22"),
    strategyId: "seo-bluepeak-01",
    projectId: "proj-bluepeak",
    pageType: "location",
    title: "Roof Repair in Austin",
    targetAudience: "Homeowners with urgent roof issues",
    intent: "transactional",
    primaryKeyword: "roof repair austin",
    secondaryKeywords: ["roof leak repair austin", "storm repair austin"],
    targetLocation: "Austin",
    ctaGoal: "Call now for inspection",
    trustElementsNeeded: ["Local project photos", "Response time promise", "Warranty snippet"],
    notes: "Lead with emergency response and financing options.",
    status: "brief-ready",
    locationPriorityScore: 95,
    internalLinkRecommendation: "Link to financing and emergency response pages.",
  },
  {
    id: "plan-luna-mesa-injury",
    createdAt: ts("2026-04-11"),
    updatedAt: ts("2026-04-22"),
    strategyId: "seo-luna-01",
    projectId: "proj-luna",
    pageType: "location",
    title: "Personal Injury Lawyer in Mesa",
    targetAudience: "Injury claim prospects seeking legal representation",
    intent: "commercial",
    primaryKeyword: "personal injury lawyer mesa",
    secondaryKeywords: ["accident attorney mesa", "injury consultation mesa"],
    targetLocation: "Mesa",
    ctaGoal: "Schedule consultation",
    trustElementsNeeded: ["Case outcomes", "Attorney credentials", "Client testimonials"],
    notes: "Ensure city-specific case context to avoid template duplication.",
    status: "planned",
    locationPriorityScore: 84,
    duplicationRiskWarning: "Current draft repeats 70% of Scottsdale page section copy.",
    thinPageRiskWarning: "Insufficient local proof and FAQs.",
    internalLinkRecommendation: "Link to Mesa case outcomes and fee explainer.",
  },
];

const pageBriefs: PageBrief[] = [
  {
    id: "brief-bluepeak-repair-austin",
    createdAt: ts("2026-04-12"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-bluepeak",
    strategyId: "seo-bluepeak-01",
    plannedPageId: "plan-bluepeak-austin-repair",
    briefType: "location-page",
    title: "Austin Roof Repair Conversion Brief",
    pageObjective: "Convert emergency local searches into booked inspections.",
    audience: "Homeowners with urgent roof leaks or storm damage",
    searchIntent: "transactional",
    primaryKeyword: "roof repair austin",
    secondaryKeywords: ["storm roof repair austin", "emergency roofer austin"],
    conversionGoal: "Call-in consultations",
    cta: "Call now for same-day inspection",
    trustProofElements: ["Before/after photos", "Local review snippets", "License + insurance"],
    objectionsToAddress: ["price concerns", "timeline uncertainty"],
    messagingAngle: "Fast response + transparent pricing + local trust",
    sectionOutline: [
      "Hero with urgency CTA",
      "Local roof issue scenarios",
      "Process and response timeline",
      "Proof and testimonials",
      "FAQ",
      "CTA",
    ],
    faqTargets: ["How quickly can you inspect?", "Do you help with insurance claims?"],
    internalNotes: "Position financing card above fold on mobile.",
    requiredAssets: ["3 local project photos", "technician headshots"],
    status: "ready",
  },
  {
    id: "brief-luna-home",
    createdAt: ts("2026-04-13"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-luna",
    strategyId: "seo-luna-01",
    briefType: "home-page",
    title: "Luna Legal Homepage Brief",
    pageObjective: "Drive consultation requests while clarifying practice area fit.",
    audience: "Prospects evaluating legal representation options",
    searchIntent: "commercial",
    primaryKeyword: "phoenix personal injury law firm",
    secondaryKeywords: ["employment law attorney phoenix", "legal consultation phoenix"],
    conversionGoal: "Consultation form submissions",
    cta: "Request consultation",
    trustProofElements: ["Attorney credentials", "Case results", "Client outcomes"],
    objectionsToAddress: ["uncertain legal costs", "fit uncertainty"],
    messagingAngle: "Clear outcomes + approachable legal guidance",
    sectionOutline: ["Hero", "Practice highlights", "Proof", "Process", "FAQ", "CTA"],
    faqTargets: ["How does your fee model work?"],
    internalNotes: "Need partner bios approved before final copy handoff.",
    requiredAssets: ["Updated partner photos", "case result snapshots"],
    status: "draft",
  },
];

const contentBriefs: ContentBrief[] = [
  {
    id: "content-brief-bluepeak-01",
    createdAt: ts("2026-04-12"),
    updatedAt: ts("2026-04-22"),
    pageBriefId: "brief-bluepeak-repair-austin",
    title: "Austin Roof Repair Draft Copy",
    writerOwner: "Dana",
    dueDate: "2026-04-26",
    status: "in-review",
  },
  {
    id: "content-brief-luna-01",
    createdAt: ts("2026-04-13"),
    updatedAt: ts("2026-04-22"),
    pageBriefId: "brief-luna-home",
    title: "Luna Homepage Messaging Draft",
    writerOwner: "Kai",
    dueDate: "2026-04-29",
    status: "draft",
  },
];

const reports: Report[] = [
  {
    id: "report-bluepeak-2026-03",
    createdAt: ts("2026-04-02"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-bluepeak",
    clientName: "BluePeak Roofing",
    periodStart: "2026-03-01",
    periodEnd: "2026-03-31",
    kpiSummary: "Qualified leads rose and local visibility improved in core service areas.",
    wins: ["Higher conversion rate on emergency pages", "Map profile interactions up 18%"],
    concerns: ["Secondary locations still lag in visibility"],
    recommendations: ["Publish 2 location pages", "Expand FAQ markup coverage"],
    nextMonthPriorities: ["Launch Austin repair page", "Improve Round Rock internal links"],
    internalNotes: "Watch lead quality consistency by zip code.",
    clientSafeSummary: "Strong momentum with clear next steps focused on local growth.",
    status: "final",
  },
  {
    id: "report-luna-2026-03",
    createdAt: ts("2026-04-03"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-luna",
    clientName: "Luna Legal Group",
    periodStart: "2026-03-01",
    periodEnd: "2026-03-31",
    kpiSummary: "Engagement improved, but local intent page depth remains incomplete.",
    wins: ["Homepage engagement up", "Consultation form completion improved"],
    concerns: ["Missing location page depth for Mesa and Scottsdale"],
    recommendations: ["Finalize location page briefs", "Add city-specific FAQs"],
    nextMonthPriorities: ["Approve design direction", "Publish 1 city page"],
    internalNotes: "Risk of delays if bios remain incomplete.",
    clientSafeSummary: "Positive engagement trend with focused local content priorities next month.",
    status: "draft",
  },
];

const reportSections: ReportSection[] = [
  {
    id: "section-bluepeak-seo",
    createdAt: ts("2026-04-02"),
    updatedAt: ts("2026-04-22"),
    reportId: "report-bluepeak-2026-03",
    category: "seo-performance",
    summary: "Core service keywords improved in rank and click-through.",
    observations: ["Emergency cluster moved from position 11 to 6"],
  },
  {
    id: "section-bluepeak-local",
    createdAt: ts("2026-04-02"),
    updatedAt: ts("2026-04-22"),
    reportId: "report-bluepeak-2026-03",
    category: "local-visibility-observations",
    summary: "Local pack visibility improved in Austin.",
    observations: ["Austin local impressions increased 14%"],
  },
  {
    id: "section-luna-content",
    createdAt: ts("2026-04-03"),
    updatedAt: ts("2026-04-22"),
    reportId: "report-luna-2026-03",
    category: "content-progress",
    summary: "Content framework in progress with pending client dependencies.",
    observations: ["Practice-area draft framework complete"],
  },
];

const sops: Sop[] = [
  {
    id: "sop-local-seo-plan",
    createdAt: ts("2026-04-04"),
    updatedAt: ts("2026-04-22"),
    title: "Local SEO Service x Location Planning",
    category: "local-seo-page-planning",
    purpose: "Create non-duplicative local page plans with clear conversion intent.",
    owner: "Maya Lee",
    status: "active",
    linkedServiceType: "SEO",
    linkedPhase: "strategy",
    notes: "Run duplication and thin-page checks before brief signoff.",
  },
  {
    id: "sop-report-qc",
    createdAt: ts("2026-04-01"),
    updatedAt: ts("2026-04-22"),
    title: "Monthly Report QA",
    category: "reporting",
    purpose: "Ensure every report has clear wins, concerns, and next-month priorities.",
    owner: "Jordan Price",
    status: "active",
    linkedServiceType: "Retention",
    linkedPhase: "post-launch",
    notes: "Internal notes must never leak into client-safe summary blocks.",
  },
];

const sopSteps: SopStep[] = [
  {
    id: "sop-step-1",
    createdAt: ts("2026-04-04"),
    updatedAt: ts("2026-04-22"),
    sopId: "sop-local-seo-plan",
    stepOrder: 1,
    stepTitle: "Build service x location matrix",
    checklist: ["List top services", "Rank locations by opportunity", "Map target intent per page"],
  },
  {
    id: "sop-step-2",
    createdAt: ts("2026-04-04"),
    updatedAt: ts("2026-04-22"),
    sopId: "sop-local-seo-plan",
    stepOrder: 2,
    stepTitle: "Run risk checks",
    checklist: ["Check duplication risk", "Check thin-page risk", "Add internal link recommendations"],
  },
  {
    id: "sop-step-3",
    createdAt: ts("2026-04-01"),
    updatedAt: ts("2026-04-22"),
    sopId: "sop-report-qc",
    stepOrder: 1,
    stepTitle: "Draft and quality check report",
    checklist: ["Draft KPI summary", "Validate recommendations", "Create client-safe summary"],
  },
];

const aiGenerations: AiGeneration[] = [
  {
    id: "ai-001",
    createdAt: ts("2026-04-20"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-bluepeak",
    action: "detect-local-seo-risks",
    inputContext: "Austin and Round Rock location pages share many repeated sections.",
    outputDraft: "AI draft flagged duplication across two location pages and recommended unique local trust blocks.",
    outputStructured: {
      risks: ["duplication", "thin-page"],
      recommendation: "Add city-specific project proof and localized FAQs",
    },
    humanReviewed: true,
    reviewer: "Maya Lee",
  },
];

export const phase3Seed = {
  seoStrategies,
  keywordClusters,
  plannedPages,
  pageBriefs,
  contentBriefs,
  reports,
  reportSections,
  sops,
  sopSteps,
  aiGenerations,
};
