import {
  Approval,
  ApprovalEvent,
  Blocker,
  ChangeRequest,
  ClientPortalVisibilityRule,
  DeliveryItem,
  OnboardingItem,
  OnboardingWorkspace,
  Project,
  ProjectMilestone,
  ProjectPhase,
  ProjectUpdate,
} from "@/lib/agency-os/domain/types";

function ts(day: string): string {
  return `${day}T12:00:00.000Z`;
}

const projects: Project[] = [
  {
    id: "proj-bluepeak",
    createdAt: ts("2026-03-25"),
    updatedAt: ts("2026-04-22"),
    title: "BluePeak Roofing Website + Lead Intake",
    clientName: "BluePeak Roofing",
    contactName: "Ava Collins",
    linkedProposalId: "proposal-bluepeak-01",
    linkedOnboardingWorkspaceId: "onboard-bluepeak",
    currentPhase: "development",
    status: "active",
    owner: "Maya Lee",
    startDate: "2026-03-28",
    targetLaunchDate: "2026-05-03",
    targetPostLaunchDate: "2026-05-20",
    internalNotes: "Upsell conversation likely after launch if lead quality improves.",
    clientSummary: "Development is underway and launch prep is in progress.",
  },
  {
    id: "proj-luna",
    createdAt: ts("2026-03-18"),
    updatedAt: ts("2026-04-22"),
    title: "Luna Legal Conversion Platform",
    clientName: "Luna Legal Group",
    contactName: "Mila Romero",
    linkedProposalId: "proposal-luna-01",
    linkedOnboardingWorkspaceId: "onboard-luna",
    currentPhase: "design",
    status: "at-risk",
    owner: "Jordan Price",
    startDate: "2026-03-20",
    targetLaunchDate: "2026-05-15",
    targetPostLaunchDate: "2026-06-01",
    internalNotes: "Content dependency delay increasing timeline risk.",
    clientSummary: "Design revisions and final content alignment are currently in progress.",
  },
  {
    id: "proj-freshpath",
    createdAt: ts("2026-04-01"),
    updatedAt: ts("2026-04-22"),
    title: "FreshPath Dental Booking Funnel",
    clientName: "FreshPath Dental",
    contactName: "Noah Patel",
    linkedProposalId: "proposal-freshpath-01",
    linkedOnboardingWorkspaceId: "onboard-freshpath",
    currentPhase: "qa",
    status: "active",
    owner: "Sam Ortega",
    startDate: "2026-04-03",
    targetLaunchDate: "2026-04-30",
    targetPostLaunchDate: "2026-05-12",
    internalNotes: "Need legal signoff on intake form wording.",
    clientSummary: "QA testing is in progress ahead of scheduled launch.",
  },
];

const projectPhases: ProjectPhase[] = [
  "strategy",
  "content",
  "design",
  "development",
  "qa",
  "launch",
  "post-launch",
].flatMap((phase, idx) =>
  projects.map((project) => ({
    id: `phase-${project.id}-${phase}`,
    createdAt: ts("2026-03-20"),
    updatedAt: ts("2026-04-22"),
    projectId: project.id,
    phase,
    startedAt: idx <= 2 ? ts("2026-03-25") : undefined,
    completedAt:
      idx < ["strategy", "content", "design", "development", "qa", "launch", "post-launch"].indexOf(
        project.currentPhase,
      )
        ? ts("2026-04-01")
        : undefined,
  })),
);

const projectMilestones: ProjectMilestone[] = [
  {
    id: "mile-bluepeak-1",
    createdAt: ts("2026-03-29"),
    updatedAt: ts("2026-04-15"),
    projectId: "proj-bluepeak",
    title: "Content architecture approved",
    dueDate: "2026-04-12",
    completedAt: "2026-04-11",
    owner: "Maya Lee",
    clientVisible: true,
  },
  {
    id: "mile-bluepeak-2",
    createdAt: ts("2026-04-03"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-bluepeak",
    title: "Development complete",
    dueDate: "2026-04-25",
    owner: "Maya Lee",
    clientVisible: true,
  },
  {
    id: "mile-luna-1",
    createdAt: ts("2026-03-25"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-luna",
    title: "Design concept signoff",
    dueDate: "2026-04-14",
    owner: "Jordan Price",
    clientVisible: true,
  },
  {
    id: "mile-luna-2",
    createdAt: ts("2026-04-08"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-luna",
    title: "Content handoff complete",
    dueDate: "2026-04-16",
    owner: "Jordan Price",
    clientVisible: true,
  },
  {
    id: "mile-freshpath-1",
    createdAt: ts("2026-04-06"),
    updatedAt: ts("2026-04-18"),
    projectId: "proj-freshpath",
    title: "QA completion",
    dueDate: "2026-04-24",
    owner: "Sam Ortega",
    clientVisible: true,
  },
  {
    id: "mile-freshpath-2",
    createdAt: ts("2026-04-10"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-freshpath",
    title: "Launch readiness",
    dueDate: "2026-04-28",
    owner: "Sam Ortega",
    clientVisible: true,
  },
];

const deliveryItems: DeliveryItem[] = [
  {
    id: "task-bluepeak-1",
    createdAt: ts("2026-04-01"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-bluepeak",
    phase: "development",
    taskGroup: "Conversion",
    title: "Implement lead routing workflow",
    owner: "Maya Lee",
    status: "in-progress",
    dependencyIds: ["task-bluepeak-2"],
    dependencyOwner: "client",
    clientVisible: false,
    internalNotes: "Blocked on CRM webhook key.",
  },
  {
    id: "task-bluepeak-2",
    createdAt: ts("2026-04-02"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-bluepeak",
    phase: "development",
    taskGroup: "Assets",
    title: "Collect final brand photo set",
    owner: "Ava Collins",
    status: "blocked",
    dependencyIds: [],
    dependencyOwner: "client",
    clientVisible: true,
  },
  {
    id: "task-luna-1",
    createdAt: ts("2026-03-30"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-luna",
    phase: "design",
    taskGroup: "Design",
    title: "Finalize homepage variant",
    owner: "Jordan Price",
    status: "blocked",
    dependencyIds: [],
    dependencyOwner: "client",
    clientVisible: true,
  },
  {
    id: "task-freshpath-1",
    createdAt: ts("2026-04-12"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-freshpath",
    phase: "qa",
    taskGroup: "QA",
    title: "Validate booking conversion events",
    owner: "Sam Ortega",
    status: "in-progress",
    dependencyIds: [],
    dependencyOwner: "internal",
    clientVisible: false,
  },
];

const blockers: Blocker[] = [
  {
    id: "block-luna-content",
    createdAt: ts("2026-04-12"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-luna",
    title: "Attorney bios incomplete",
    description: "Missing finalized attorney bios prevents template finalization.",
    status: "open",
    owner: "Mila Romero",
    dependencyOwner: "client",
    openedAt: "2026-04-12",
  },
  {
    id: "block-bluepeak-access",
    createdAt: ts("2026-04-19"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-bluepeak",
    title: "CRM webhook credentials missing",
    description: "Webhook secret key has not been shared.",
    status: "open",
    owner: "Ava Collins",
    dependencyOwner: "client",
    openedAt: "2026-04-19",
  },
];

const approvals: Approval[] = [
  {
    id: "approval-bluepeak-prelaunch",
    createdAt: ts("2026-04-18"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-bluepeak",
    title: "Pre-launch QA signoff",
    type: "pre-launch-approval",
    deliverableRef: "doc://qa-report-bluepeak-v2",
    requestedFrom: "Ava Collins",
    requestedDate: "2026-04-20",
    dueDate: "2026-04-23",
    status: "requested",
    internalNotes: "Without signoff launch date may slip by 2 days.",
    clientMessage: "Please review the QA report and confirm launch readiness.",
  },
  {
    id: "approval-luna-design",
    createdAt: ts("2026-04-10"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-luna",
    title: "Homepage design direction",
    type: "design-approval",
    deliverableRef: "figma://luna-home-v4",
    requestedFrom: "Mila Romero",
    requestedDate: "2026-04-11",
    dueDate: "2026-04-15",
    status: "requested",
    internalNotes: "This is gating development kickoff.",
    clientMessage: "Please choose your preferred homepage direction so we can continue.",
  },
  {
    id: "approval-freshpath-launch",
    createdAt: ts("2026-04-16"),
    updatedAt: ts("2026-04-21"),
    projectId: "proj-freshpath",
    title: "Launch approval",
    type: "launch-approval",
    deliverableRef: "doc://launch-checklist-freshpath",
    requestedFrom: "Noah Patel",
    requestedDate: "2026-04-20",
    dueDate: "2026-04-27",
    status: "requested",
    internalNotes: "Need legal review complete first.",
    clientMessage: "Confirm launch timing and checklist approval.",
  },
];

const approvalEvents: ApprovalEvent[] = [
  {
    id: "appevent-1",
    createdAt: ts("2026-04-11"),
    updatedAt: ts("2026-04-11"),
    approvalId: "approval-luna-design",
    eventType: "requested",
    actor: "Jordan Price",
    message: "Design approval requested with due date April 15.",
  },
  {
    id: "appevent-2",
    createdAt: ts("2026-04-20"),
    updatedAt: ts("2026-04-20"),
    approvalId: "approval-bluepeak-prelaunch",
    eventType: "requested",
    actor: "Maya Lee",
    message: "Pre-launch QA report sent for review.",
  },
];

const changeRequests: ChangeRequest[] = [
  {
    id: "cr-luna-1",
    createdAt: ts("2026-04-19"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-luna",
    requestTitle: "Add attorney profile filters",
    requestDescription: "Client wants category filters and attorney sorting on profile pages.",
    requestedBy: "Mila Romero",
    dateSubmitted: "2026-04-19",
    status: "reviewing",
    impactSummary: "Additional front-end and CMS structure changes required.",
    timelineImpactDays: 4,
    costImpact: "TBD",
    internalAssessment: "Likely out of current scope without reducing another feature.",
    clientSummary: "We are assessing timeline and effort impact.",
  },
  {
    id: "cr-bluepeak-1",
    createdAt: ts("2026-04-17"),
    updatedAt: ts("2026-04-20"),
    projectId: "proj-bluepeak",
    requestTitle: "Add financing calculator",
    requestDescription: "Client requested a financing calculator on service pages.",
    requestedBy: "Ava Collins",
    dateSubmitted: "2026-04-17",
    status: "deferred",
    impactSummary: "Requires custom logic and legal review.",
    timelineImpactDays: 6,
    costImpact: "TBD",
    internalAssessment: "Move to post-launch sprint recommended.",
    clientSummary: "Recommended for post-launch to protect current timeline.",
    decisionResult: "Deferred to post-launch phase.",
  },
];

const onboardingWorkspaces: OnboardingWorkspace[] = [
  {
    id: "onboard-bluepeak",
    createdAt: ts("2026-03-28"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-bluepeak",
    clientName: "BluePeak Roofing",
    kickoffDate: "2026-04-02",
    kickoffReadiness: "at-risk",
    internalNotes: "Credentials collection incomplete.",
    nextStepsClient: "Upload final brand assets and CRM access credentials.",
  },
  {
    id: "onboard-luna",
    createdAt: ts("2026-03-22"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-luna",
    clientName: "Luna Legal Group",
    kickoffDate: "2026-03-26",
    kickoffReadiness: "blocked",
    internalNotes: "Content and legal approvals are blocking delivery.",
    nextStepsClient: "Complete attorney bios and approve homepage direction.",
  },
  {
    id: "onboard-freshpath",
    createdAt: ts("2026-04-03"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-freshpath",
    clientName: "FreshPath Dental",
    kickoffDate: "2026-04-05",
    kickoffReadiness: "ready",
    internalNotes: "Onboarding dependencies mostly complete.",
    nextStepsClient: "Review launch checklist and approve launch window.",
  },
];

const onboardingItems: OnboardingItem[] = [
  {
    id: "onitem-bluepeak-assets",
    createdAt: ts("2026-03-29"),
    updatedAt: ts("2026-04-22"),
    workspaceId: "onboard-bluepeak",
    projectId: "proj-bluepeak",
    category: "assets",
    title: "Upload final project photos",
    description: "Provide at least 20 high-resolution project images.",
    status: "pending",
    waitingOn: "client",
    dueDate: "2026-04-23",
    clientVisible: true,
    internalNotes: "Blocking final page polish.",
  },
  {
    id: "onitem-bluepeak-tech",
    createdAt: ts("2026-03-29"),
    updatedAt: ts("2026-04-20"),
    workspaceId: "onboard-bluepeak",
    projectId: "proj-bluepeak",
    category: "technical-access",
    title: "Provide CRM webhook key",
    description: "Share webhook secret for lead routing integration.",
    status: "blocked",
    waitingOn: "client",
    dueDate: "2026-04-21",
    clientVisible: true,
    internalNotes: "Critical blocker for launch automation.",
  },
  {
    id: "onitem-luna-content",
    createdAt: ts("2026-03-25"),
    updatedAt: ts("2026-04-22"),
    workspaceId: "onboard-luna",
    projectId: "proj-luna",
    category: "content",
    title: "Submit attorney bios",
    description: "Complete bios for all practice leads.",
    status: "blocked",
    waitingOn: "client",
    dueDate: "2026-04-15",
    clientVisible: true,
    internalNotes: "Missing bios are causing phase delay.",
  },
  {
    id: "onitem-freshpath-approvals",
    createdAt: ts("2026-04-10"),
    updatedAt: ts("2026-04-20"),
    workspaceId: "onboard-freshpath",
    projectId: "proj-freshpath",
    category: "approvals",
    title: "Approve intake form legal text",
    description: "Confirm legal language before launch.",
    status: "submitted",
    waitingOn: "internal",
    dueDate: "2026-04-24",
    clientVisible: true,
  },
];

const projectUpdates: ProjectUpdate[] = [
  {
    id: "update-bluepeak-1",
    createdAt: ts("2026-04-21"),
    updatedAt: ts("2026-04-21"),
    projectId: "proj-bluepeak",
    summary: "QA passed on lead forms; waiting on CRM credentials for final integration.",
    audience: "client",
    createdBy: "Maya Lee",
  },
  {
    id: "update-luna-1",
    createdAt: ts("2026-04-20"),
    updatedAt: ts("2026-04-20"),
    projectId: "proj-luna",
    summary: "Design revisions prepared; awaiting homepage direction approval.",
    audience: "client",
    createdBy: "Jordan Price",
  },
  {
    id: "update-luna-int-1",
    createdAt: ts("2026-04-21"),
    updatedAt: ts("2026-04-21"),
    projectId: "proj-luna",
    summary: "Potential scope pressure from profile filter change request.",
    audience: "internal",
    createdBy: "Jordan Price",
  },
];

const clientPortalVisibility: ClientPortalVisibilityRule[] = [
  "proj-bluepeak",
  "proj-luna",
  "proj-freshpath",
].flatMap((projectId) =>
  (["milestones", "approvals", "onboarding", "updates", "files"] as const).map((resource) => ({
    id: `vis-${projectId}-${resource}`,
    createdAt: ts("2026-03-25"),
    updatedAt: ts("2026-03-25"),
    projectId,
    resource,
    visible: true,
  })),
);

export const seed = {
  projects,
  projectPhases,
  projectMilestones,
  deliveryItems,
  blockers,
  approvals,
  approvalEvents,
  changeRequests,
  onboardingWorkspaces,
  onboardingItems,
  projectUpdates,
  clientPortalVisibility,
};
