import {
  AuditLog,
  AutomationLog,
  AutomationRule,
  ClientHealth,
  CommunicationMessage,
  DealValue,
  DerivedMetric,
  ExpansionOpportunity,
  IntegrationConfig,
  PipelineSnapshot,
  RetentionSignal,
} from "@/lib/agency-os/phase4/types";

function ts(day: string): string {
  return `${day}T12:00:00.000Z`;
}

const automationRules: AutomationRule[] = [
  {
    id: "auto-approval-overdue-flag",
    createdAt: ts("2026-04-12"),
    updatedAt: ts("2026-04-22"),
    name: "Flag project when approval is overdue",
    trigger: "approval-overdue",
    conditionSummary: "Any requested approval past due date by 1+ day",
    actions: ["flag-project", "create-notification", "assign-owner"],
    owner: "Ops System",
    status: "enabled",
  },
  {
    id: "auto-onboarding-reminder",
    createdAt: ts("2026-04-10"),
    updatedAt: ts("2026-04-22"),
    name: "Send onboarding reminder after inactivity",
    trigger: "onboarding-incomplete",
    conditionSummary: "Onboarding item pending > 3 days and waiting on client",
    actions: ["send-email", "generate-follow-up-draft"],
    owner: "Account Ops",
    status: "enabled",
  },
  {
    id: "auto-proposal-followup",
    createdAt: ts("2026-04-08"),
    updatedAt: ts("2026-04-22"),
    name: "Proposal no-response follow-up",
    trigger: "proposal-no-response",
    conditionSummary: "Proposal sent with no response after 5 days",
    actions: ["generate-follow-up-draft", "create-task"],
    owner: "Sales Ops",
    status: "enabled",
  },
];

const automationLogs: AutomationLog[] = [
  {
    id: "alog-1",
    createdAt: ts("2026-04-21"),
    updatedAt: ts("2026-04-21"),
    automationId: "auto-approval-overdue-flag",
    trigger: "approval-overdue",
    projectId: "proj-luna",
    matched: true,
    result: "matched",
    details: "Design approval overdue by 7 days. Project flagged at-risk.",
    executedActions: ["flag-project", "create-notification"],
  },
  {
    id: "alog-2",
    createdAt: ts("2026-04-21"),
    updatedAt: ts("2026-04-21"),
    automationId: "auto-onboarding-reminder",
    trigger: "onboarding-incomplete",
    projectId: "proj-bluepeak",
    matched: true,
    result: "matched",
    details: "Technical access item pending and waiting on client.",
    executedActions: ["send-email", "generate-follow-up-draft"],
  },
];

const dealValues: DealValue[] = [
  {
    id: "deal-bluepeak",
    createdAt: ts("2026-04-01"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-bluepeak",
    clientName: "BluePeak Roofing",
    serviceType: "Website + Lead Ops",
    stage: "negotiating",
    dealValue: 14500,
    probabilityPct: 72,
    expectedRevenue: 10440,
    isRetainer: true,
    monthlyRecurringValue: 1200,
  },
  {
    id: "deal-luna",
    createdAt: ts("2026-03-25"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-luna",
    clientName: "Luna Legal Group",
    serviceType: "Conversion Platform",
    stage: "sent",
    dealValue: 33200,
    probabilityPct: 64,
    expectedRevenue: 21248,
    isRetainer: false,
  },
  {
    id: "deal-freshpath",
    createdAt: ts("2026-04-03"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-freshpath",
    clientName: "FreshPath Dental",
    serviceType: "Booking Funnel",
    stage: "won",
    dealValue: 9800,
    probabilityPct: 100,
    expectedRevenue: 9800,
    isRetainer: true,
    monthlyRecurringValue: 950,
  },
];

const pipelineSnapshots: PipelineSnapshot[] = [
  {
    id: "pipe-snap-2026-04-22",
    createdAt: ts("2026-04-22"),
    updatedAt: ts("2026-04-22"),
    totalPipelineValue: 57500,
    weightedPipelineValue: 41488,
    wonValue: 9800,
    lostValue: 0,
    projectedNext30Days: 21248,
  },
];

const retentionSignals: RetentionSignal[] = [
  {
    id: "ret-luna-approval",
    createdAt: ts("2026-04-20"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-luna",
    signalType: "delayed-approvals",
    severity: 3,
    note: "Design approval overdue by one week.",
  },
  {
    id: "ret-bluepeak-onboard",
    createdAt: ts("2026-04-20"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-bluepeak",
    signalType: "stalled-onboarding",
    severity: 2,
    note: "Technical access item unresolved.",
  },
  {
    id: "ret-luna-change",
    createdAt: ts("2026-04-21"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-luna",
    signalType: "repeated-change-requests",
    severity: 2,
    note: "Additional scope requests still in review.",
  },
];

const clientHealth: ClientHealth[] = [
  {
    id: "health-bluepeak",
    createdAt: ts("2026-04-22"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-bluepeak",
    clientName: "BluePeak Roofing",
    score: 72,
    level: "yellow",
    riskFlags: ["onboarding dependency pending"],
    engagementSignals: ["responds within 48h", "active in approvals"],
  },
  {
    id: "health-luna",
    createdAt: ts("2026-04-22"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-luna",
    clientName: "Luna Legal Group",
    score: 54,
    level: "red",
    riskFlags: ["overdue approvals", "scope-change churn"],
    engagementSignals: ["response delays > 5 days"],
  },
  {
    id: "health-freshpath",
    createdAt: ts("2026-04-22"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-freshpath",
    clientName: "FreshPath Dental",
    score: 86,
    level: "green",
    riskFlags: [],
    engagementSignals: ["fast feedback", "clear approvals"],
  },
];

const expansionOpportunities: ExpansionOpportunity[] = [
  {
    id: "expand-bluepeak-local-seo",
    createdAt: ts("2026-04-22"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-bluepeak",
    clientName: "BluePeak Roofing",
    serviceSuggestion: "Local SEO monthly package",
    rationale: "Location pages and map profile improvements are showing traction.",
    confidence: "high",
    nextOpportunityNote: "Present after first post-launch report.",
  },
  {
    id: "expand-freshpath-content",
    createdAt: ts("2026-04-22"),
    updatedAt: ts("2026-04-22"),
    projectId: "proj-freshpath",
    clientName: "FreshPath Dental",
    serviceSuggestion: "Quarterly content growth sprint",
    rationale: "Strong conversion baseline can benefit from topical expansion.",
    confidence: "medium",
    nextOpportunityNote: "Bundle with reporting cadence renewal.",
  },
];

const communicationMessages: CommunicationMessage[] = [
  {
    id: "msg-approval-luna-1",
    createdAt: ts("2026-04-21"),
    updatedAt: ts("2026-04-21"),
    type: "approval-request",
    projectId: "proj-luna",
    clientName: "Luna Legal Group",
    subject: "Action required: homepage direction approval",
    bodyDraft: "Please approve the selected homepage direction by Friday to keep launch timing on track.",
    editableBody: "Please review and approve the homepage direction by Friday so we can keep the project timeline stable.",
    status: "draft",
    generatedByAi: true,
  },
  {
    id: "msg-report-bluepeak-1",
    createdAt: ts("2026-04-22"),
    updatedAt: ts("2026-04-22"),
    type: "report-delivery",
    projectId: "proj-bluepeak",
    clientName: "BluePeak Roofing",
    subject: "March performance report is ready",
    bodyDraft: "Your monthly report is ready with wins, risks, and next-month priorities.",
    editableBody: "Your March report is ready. It includes performance highlights, key concerns, and next-month priorities.",
    status: "sent",
    sentAt: ts("2026-04-22"),
    generatedByAi: false,
  },
];

const integrationsConfig: IntegrationConfig[] = [
  {
    id: "int-resend",
    createdAt: ts("2026-04-10"),
    updatedAt: ts("2026-04-22"),
    provider: "resend",
    enabled: true,
    status: "connected",
    notes: "Primary transactional email provider for workflow messages.",
  },
  {
    id: "int-gsc",
    createdAt: ts("2026-04-12"),
    updatedAt: ts("2026-04-22"),
    provider: "google-search-console",
    enabled: false,
    status: "not-configured",
    notes: "Optional Phase 4 light integration for SEO snapshots.",
  },
  {
    id: "int-ga",
    createdAt: ts("2026-04-12"),
    updatedAt: ts("2026-04-22"),
    provider: "google-analytics",
    enabled: false,
    status: "not-configured",
    notes: "Optional Phase 4 light integration for site performance snapshots.",
  },
];

const derivedMetrics: DerivedMetric[] = [
  {
    id: "metric-close-rate-web",
    createdAt: ts("2026-04-22"),
    updatedAt: ts("2026-04-22"),
    metricKey: "service_close_rate_web",
    metricLabel: "Web + Funnel close performance",
    value: 64,
    unit: "percent",
    interpretation: "Website + funnel packages close more reliably than mixed-scope proposals.",
  },
  {
    id: "metric-avg-launch-days",
    createdAt: ts("2026-04-22"),
    updatedAt: ts("2026-04-22"),
    metricKey: "avg_days_to_launch",
    metricLabel: "Average time to launch",
    value: 43,
    unit: "days",
    interpretation: "Main delays occur during client approvals and onboarding dependencies.",
  },
  {
    id: "metric-scope-creep-rate",
    createdAt: ts("2026-04-22"),
    updatedAt: ts("2026-04-22"),
    metricKey: "scope_creep_rate",
    metricLabel: "Projects with change-request pressure",
    value: 33,
    unit: "percent",
    interpretation: "Scope pressure clusters around design and local-page expansion stages.",
  },
];

const auditLogs: AuditLog[] = [
  {
    id: "audit-automation-toggle",
    createdAt: ts("2026-04-21"),
    updatedAt: ts("2026-04-21"),
    actor: "Maya Lee",
    role: "ops",
    action: "toggle_automation",
    entityType: "automation",
    entityId: "auto-approval-overdue-flag",
    summary: "Automation confirmed enabled after QA review.",
  },
  {
    id: "audit-message-send",
    createdAt: ts("2026-04-22"),
    updatedAt: ts("2026-04-22"),
    actor: "Jordan Price",
    role: "account-manager",
    action: "send_message",
    entityType: "communication_message",
    entityId: "msg-report-bluepeak-1",
    summary: "Monthly report delivery email sent.",
  },
];

export const phase4Seed = {
  automationRules,
  automationLogs,
  dealValues,
  pipelineSnapshots,
  retentionSignals,
  clientHealth,
  expansionOpportunities,
  communicationMessages,
  integrationsConfig,
  derivedMetrics,
  auditLogs,
};
